//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnjoyOurTour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string NRIC { get; set; }
        public string BankAccountNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public int AvailableTVR { get; set; }
        public decimal AvailableAmount { get; set; }
        public int AvailablePoint { get; set; }
        public int AgentId { get; set; }
        public Nullable<int> IntroducerId { get; set; }
        public System.DateTime JoinDate { get; set; }
        public int UserId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime RenewDate { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public string BankName { get; set; }
        public int IntroduceTimes { get; set; }
    }
}
