//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnjoyOurTour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        public int MerchantId { get; set; }
        public string MerchantName { get; set; }
        public string MerchantRegisterCode { get; set; }
        public string MerchantPhoneNumber { get; set; }
        public string MerchantAddress { get; set; }
        public int MerchantCategoryId { get; set; }
        public System.DateTime MerchantJoinDate { get; set; }
        public string MerchantLogoPath { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    }
}
