//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnjoyOurTour.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourEntities : DbContext
    {
        public TourEntities()
            : base("name=TourEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutUs> AboutUs { get; set; }
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<AgentTransaction> AgentTransaction { get; set; }
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<ContactUs> ContactUs { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<CustomersTestimony> CustomersTestimony { get; set; }
        public virtual DbSet<GoodNews> GoodNews { get; set; }
        public virtual DbSet<IntroducerTransaction> IntroducerTransaction { get; set; }
        public virtual DbSet<Merchant> Merchant { get; set; }
        public virtual DbSet<MerchantCategory> MerchantCategory { get; set; }
        public virtual DbSet<MerchantPromotion> MerchantPromotion { get; set; }
        public virtual DbSet<Package> Package { get; set; }
        public virtual DbSet<ProductRedeem> ProductRedeem { get; set; }
        public virtual DbSet<RedeemCoupon> RedeemCoupon { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SystemSetting> SystemSetting { get; set; }
        public virtual DbSet<TransactionActivity> TransactionActivity { get; set; }
        public virtual DbSet<TravelPromotion> TravelPromotion { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserTransaction> UserTransaction { get; set; }
        public virtual DbSet<UserTransactionStatus> UserTransactionStatus { get; set; }
        public virtual DbSet<TransactionView> TransactionView { get; set; }
        public virtual DbSet<User_Adgent> User_Adgent { get; set; }
        public virtual DbSet<User_Customer_Adgent> User_Customer_Adgent { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<RedeemCouponTransactionView> RedeemCouponTransactionView { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplate { get; set; }
    }
}
