//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnjoyOurTour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionView
    {
        public int TransactionId { get; set; }
        public string AgentCodeName { get; set; }
        public string CustomerCodeName { get; set; }
        public string IntroducerCodeName { get; set; }
        public string ReferenceNo { get; set; }
        public string ActivityName { get; set; }
        public int ActivityId { get; set; }
        public string PathForProof { get; set; }
        public decimal Amount { get; set; }
        public int CurrentTVR { get; set; }
        public int TopUpTVR { get; set; }
        public int RedeemTVR { get; set; }
        public int BalanceTVR { get; set; }
        public int CurrentPoint { get; set; }
        public int PointAdd { get; set; }
        public int PointRedeem { get; set; }
        public int PointBalance { get; set; }
        public string PackageName { get; set; }
        public Nullable<int> TravelHeadCount { get; set; }
        public string ProductRedeemName { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public int StatusId { get; set; }
        public string StatusName { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
