//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnjoyOurTour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Customer_Adgent
    {
        public int UserId { get; set; }
        public int CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public int AgentCode { get; set; }
        public string AgentName { get; set; }
        public string Username { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string NRIC { get; set; }
        public string BankName { get; set; }
        public string BankAccountNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public int AvailableTVR { get; set; }
        public decimal AvailableAmount { get; set; }
        public int AvailablePoint { get; set; }
        public string IntroduceCode { get; set; }
        public string IntroduceName { get; set; }
        public System.DateTime JoinDate { get; set; }
        public System.DateTime RenewDate { get; set; }
        public System.DateTime ExpiredDate { get; set; }
    }
}
